# Generated by Django 5.2.4 on 2025-08-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0002_alter_ticket_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(blank=True, max_length=8192),
        ),
    ]
