# Generated by Django 5.2.4 on 2025-09-05 10:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0003_alter_review_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(
                blank=True, help_text="Corps de la critique", max_length=8192
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="headline",
            field=models.CharField(help_text="Titre de la critique", max_length=128),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                help_text="Note de 0 à 5",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.ForeignKey(
                help_text="Ticket critiqué",
                on_delete=django.db.models.deletion.CASCADE,
                to="web_app.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date de création de la critique"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur ayant écrit la critique",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description détaillée du ticket", max_length=2048
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image associée au ticket",
                null=True,
                upload_to="tickets_images/",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date de création du ticket"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(help_text="Titre du ticket", max_length=128),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur ayant créé le ticket",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date d'inscription de l'utilisateur"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Indique si l'utilisateur est actif"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Indique si l'utilisateur peut accéder à l'admin",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Nom d'utilisateur unique", max_length=40, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userfollows",
            name="followed_user",
            field=models.ForeignKey(
                help_text="Utilisateur suivi",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfollows",
            name="user",
            field=models.ForeignKey(
                help_text="Utilisateur qui suit",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
